### ISSUE TITLE
Why not python?

### ISSUE THREAD

**Issue by jrsupplee** [mitchellurgero/miab_user_scripts#1]
The idea of expanded command line tools is a good one, but why not write it in python so that you can call the management libraries directly?

See `tools/mail.py` for an example.

**Comment by mitchellurgero** [comment]
Hello @jrsupplee ! I don't actually like Python all that well, however I built this script so it can be called directly like any other script on your system.  Check out line 1 `#!/usr/bin/php` As long as the script is executable, bash & dash both will follow that line and use the linked program to execute the script.

**Comment by jrsupplee** [comment]
The `tools\mail.py` file also has a shebang and can be executed from the command line.  My point in suggesting python is that the libraries for making changes to an MiaB instance are written in python.  They can be called directly without the `curl` calls and entering username and password every time.

But if you prefer PHP then use that.

One recommendation is that you can use `/var/lib/mailinabox/api.key` instead of the username and password.  And instead of making your calls through the nginx server call the management daemon directly at `localhost:10023`.  That way you do not need the hostname and you can authenticate by passing the api key appended with a colon (:) for username:password.  Look at `management/daemon.py` for what the calls should look like.

**Comment by mitchellurgero** [comment]
I appreciate the recommendation, however this script is meant to be ran remotely. In which case the user can just use the api key as the username if they like. Or maybe I can make that a command line option too down the road.
